import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//fonts
//color schemes
//header and footer or things on every page

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next App",
  author: "Daniel Freeman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1>Navigate this</h1>
        {children}
      </body>
    </html>
  );
}